blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from blog.feeds import WriterFeed

# app_name=
urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.register_user, name='register'),
    path('articles/', views.ArticleListView.as_view(), name='articles'),
    path('articles/search/', views.search, name='search'),
    path('article/create/', views.ArticleCreateView.as_view(), name='new-article'),
    path('@<str:username>/', views.WriterDetailView.as_view(), name='writer'),
    path('@<str:username>/rss/', WriterFeed(), name='rss-feed'),
    path('@<str:username>/delete', views.UserDeleteView.as_view(), name='delete-account'),
    path('@<str:username>/profile/update/', views.WriterUpdateView.as_view(), name='writer-profile-update'),
    path('@<str:username>/<slug:article_url>/', views.ArticleDetailView.as_view(), name='article-detail'),
    path('@<str:username>/<slug:article_url>/comment/', views.comment, name='article-comments'),
    path('@<str:username>/<slug:article_url>/comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='delete-comment'),
    path('@<str:username>/<slug:article_url>/comment/reply/', views.reply, name='article-comments-replies'),
    path('@<str:username>/<slug:article_url>/comment/reply/<int:pk>/delete/', views.ReplyDeleteView.as_view(), name='delete-reply'),
    path('@<str:username>/<slug:article_url>/update/', views.ArticleUpdateView.as_view(), name='update-article'),
    path('@<str:username>/<slug:article_url>/delete/', views.ArticleDeleteView.as_view(), name='delete-article'),
    path('@<str:username>/<slug:article_url>/like/', views.article_likes, name='like-article'),
    path('@<str:username>/<slug:article_url>/save/', views.save_article, name='save-article'),
    path('me/articles/filter/', views.article_filter, name='filter'),
    path('me/articles/saved/', login_required(views.ArticleListView.as_view()), name='saved-articles'),
    path('me/settings/', views.writer_settings_page, name='settings'),
    path('writer/create/', views.WriterCreateView.as_view(), name='new-writer'),
]

flove_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('email/', include(email_urls), name='email-verification'),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 404 Page handler
handler404 = 'blog.views.page_not_found'

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
# For rich text
from ckeditor.fields import RichTextField


class Writer(models.Model):
    """Class containing writer's information."""

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    profile_picture = models.ImageField(upload_to='img/user_img/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    display_email = models.BooleanField(default=False)
    website_url = models.URLField(null=True, blank=True)
    linkedin_url = models.URLField(null=True, blank=True)
    saved_articles = models.ManyToManyField("Article", related_name='saved_articles', blank=True)

    class Meta:
        """Orders writers based on their last name and first name."""
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns url of each writer."""
        return reverse('writer', kwargs={'username':self.user})

    def __str__(self):
        """Returns writer's name."""
        return f'{self.last_name} {self.first_name}'


class Article(models.Model):
    """Class for articles."""

    # Choices to make articles either draft, public, or unlisted.
    ARTICLE_STATUS = (
        ('d', 'Draft'),
        ('p', 'Public'),
        ('u', 'Unlisted'),
    )

    # Choices for writer to have article audio displayed on article detail page.
    DISPLAY_AUDIO = (
        ('y', 'Yes'),
        ('n', 'No'),
    )

    writer = models.ForeignKey(Writer, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = RichTextField()
    article_img = models.ImageField(upload_to='img/article_img/', null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True) 
    update_date = models.DateTimeField(auto_now=True)
    article_status = models.CharField(max_length=1, choices=ARTICLE_STATUS, default='d')
    article_url = models.CharField(max_length=120)
    article_audio = models.FileField(upload_to='article_audio/')
    display_audio = models.CharField(max_length=1, choices=DISPLAY_AUDIO)
    likes = models.ManyToManyField(Writer, related_name='article_likes', blank=True)
    # article_tag = models.CharField(max_length=100)


    class Meta:
        """Orders articles based on recently published."""
        ordering = ['-pub_date']

    def get_absolute_url(self):
        """Returns url of each article."""
        return reverse('article-detail', kwargs={'article_url':self.article_url, 'username':self.writer.user})

    def __str__(self):
        """Returns article title."""
        return f'{self.title} by {self.writer}'


class Comment(models.Model):
    """Class containing comments of writers."""

    text = models.TextField()
    commenter = models.ForeignKey(Writer, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Orders comments based on recently published."""
        ordering = ['-date']

    def __str__(self):
        """String name"""
        return f'{self.commenter} comment in {self.article}'


class Reply(models.Model):
    """Class containing replies to comments."""

    reply_text = models.TextField()
    replier = models.ForeignKey(Writer, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)  # Comment replied to
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Orders replies based on ascending of order of published date."""
        ordering = ['date']

    def __str__(self):
        """Returns string name"""
        return f'{self.replier} replied {self.comment}'

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from blog.models import Comment, Reply


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply_text']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist

# Models
from blog.models import Article, Writer, Comment, Reply

# Make login a requirement
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

# For user to create account and email verification to be done.
from .forms import UserRegistrationForm
from django_email_verification import send_email

# For creation of article's url
from django.utils.text import slugify
from uuid import uuid4

# For handling of text to speech for article audio.
import pyttsx3
import os

# Using rich text audio to contain hmtl tags.
# This filters our the tags and unicode characters
from django.utils.html import strip_tags    # Removes html tags
from html import unescape   # Converts unicode to Python equivalent
from unicodedata import normalize # Convert Python unicode character to text equivalent


# For calculating how long it would take to read an article
import time

# Forms for comment and reply
from blog.forms import CommentForm, ReplyForm

# For displaying error message for comments and replies
from django.contrib import messages

# For making search form
from django.db.models import Q

# For sending email notifications when an article is commented.
import django.core.mail
from flove_blog.settings import EMAIL_FROM_ADDRESS as flove_blog_email


def home(request):
    """Blog home page."""
    return redirect(reverse_lazy('articles'))


class CustomLoginView(LoginView):
    """
    Login view for users to log in. Inherits that LoginView functionality.
    """

    def form_invalid(self, form):
        """
        Checks if user is active.

        If user is not active is not active. The form is returned and
        the user is sent a mail with token to activate their account.


        Args:
            form: The login form.

        Returns:
            super().form_invalid(form): Super class functionality.
        """

        # Check if the user is not active
        try:
            username = self.request.POST['username']
            user = User.objects.filter(Q(username=username) | Q(email=username))[0]
            print(user)
            if not user.is_active:
                # Add a custom error message
                messages.error(self.request, 'This account is inactive. Please check your email to activate your account.')
                send_email(user)
        except IndexError:
            pass

        # Call the parent class's form_invalid method
        # and passing the form submitted.
        return super().form_invalid(form)


def register_user(request):
    """Registers new users."""

    form = UserRegistrationForm()

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            form.save(commit=False)
            user_email = form.cleaned_data['email']
            user_username = form.cleaned_data['username']
            user_password = form.cleaned_data['password1']

            # Check if email already exist in the database.
            try:
                email_exist = User.objects.get(email=user_email)

                if email_exist:
                    context = {
                        'form': form,
                        'email_error':'A user with this email already exists.',
                    }
                    return render(request, 'registration/register.html', context)
            except ObjectDoesNotExist:
                pass


            user = User.objects.create_user(
                username=user_username,
                email=user_email,
                password=user_password,
                )

            # Make user unactive until they click link to token in email
            user.is_active = False

            send_email(user)

            return HttpResponseRedirect(reverse('login'))

    return render(request, 'registration/register.html', {'form':form})


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Deletes user account."""

    model = User
    slug_url_kwarg = 'username'
    template_name = 'blog/user_confirm_delete.html'
    success_url = reverse_lazy('home')

    def  get_object(self, queryset=None):
        """Assigns username of the User model to the url kwarg."""

        user = self.kwargs.get(self.slug_url_kwarg)

        return get_object_or_404(self.model, username=user)
    
    def test_func(self):
        """"Works with UserPassesTestMixin.

        Returns True when current user owner of account
        but returns False when current user is not.
        """

        username = User.objects.filter(username=self.kwargs['username'])[0]
        return username == self.request.user

    def handle_no_permission(self, *kwargs):
        """Redirect current user who is not user of the account to the home page.

        By default, test_func redirects user who do not own the account to the 403 page.
        """
        
        return redirect(reverse_lazy('home'))


class ArticleListView(ListView):
    """Lists all public articles."""

    # model = Article
    template_name = 'blog/article_list.html'
    queryset = Article.objects.filter(article_status='p')
    paginate_by = 10

    def get_queryset(self, **kwargs):
        """Handles query set for both all articles and viewing saved articles.
        
        - If request is for all articles, it displays all public articles,
        else, if it is for saved articles, articles saved by 
        requesting user are displayed
        - To access saved articles, user must be logged in. This is handled
        in the urls.py file
        """
        queryset = super().get_queryset()

        current_url = self.request.path
        if current_url == reverse('articles'):
            queryset = queryset

        # Queryset for saved articles
        elif current_url == reverse('saved-articles'):

            # Check if users has created their writer profile.
            if hasattr(self.request.user, 'writer'):
                queryset = Writer.objects.get(id=self.request.user.writer.id).saved_articles.all()
            else:
                return

        return queryset


class ArticleDetailView(DetailView):
    """Display content of articles"""

    model = Article
    slug_url_kwarg = 'article_url'
    slug_url_kwarg2 = 'username'

    def get_object(self, queryset=None):
        """Function to assign field of the User model that would be used for the url kwarg."""

        article_url = self.kwargs.get(self.slug_url_kwarg)
        user_name = self.kwargs.get(self.slug_url_kwarg2)

        return get_object_or_404(self.model, article_url=article_url)

    def get_context_data(self, **kwargs):
        """Function to:
        - Add article reading time to template.
        - Add other article of the writer for reader to read.
        """
        
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Get article text and title
        article_url = self.kwargs['article_url']
        article_text = Article.objects.filter(article_url=article_url).values()[0]['text']
        article_title = Article.objects.filter(article_url=article_url).values()[0]['title']

        # Article reading time
        word_num = len(article_text.split() + article_title.split()) 
        word_secs = (word_num / 200) * 60  # 200 words per minutes

        if word_secs < 60:
            article_time  = 'Less than a minute'
        else:
            article_time = time.strftime('%M mins %S secs', time.gmtime(word_secs))

        context['article_time'] = article_time

        # More 3 recent articles by same writer for readers to read.
        writer_username = self.kwargs['username']
        user_id = User.objects.filter(username=writer_username).values()[0]['id']
        writer  = Writer.objects.get(user=user_id)

        more_article = Article.objects.filter(writer=writer).exclude(article_url=article_url).exclude(article_status='d')[:3]
        context['more_article'] = more_article

        # Addition of number of comments and replies
        comment_count =  Article.objects.filter(article_url=article_url).get().comment_set.all().count()
        reply_count =  Article.objects.filter(article_url=article_url).get().reply_set.all().count()

        total_comment = comment_count + reply_count

        context['total_comment'] = total_comment

        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """Creates new articles."""

    model = Article
    fields = ['article_img', 'title', 'text', 'article_status', 'display_audio']

    def form_valid(self, form):
        """
        - Assigns article to current user
        - Use article's title and uuid to create url path of article.
        - Create article audio using pyttsx3 module

        Args:
            form: The article creation form submitted.
        """

        # Assigns the writer field to the current user.
        user_name = self.request.user
        form.instance.writer = user_name.writer

        # Adding random hash the end of article title to make url unique.
        random_slug = str(uuid4())[:8]
        article_url_path = form.instance.title + ' ' + random_slug

blog/templates/blog/article_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>Delete {{ article.title }} | Flove</title>
{% endblock %}

{% block content %}

    <div class="body-content">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete <strong>{{ article.title }}</strong>.</p>
            {{ form }}

            <input type="submit" value="Yes">
            <input type="submit" class="delete-cancel-button" value="Cancel">
        </form>
    </div>

    <!-- Data value that would be sent to external JavaScript to cancel delete -->
    <div id="cancel-delete-redirect-to-article", data-cancel_delete_redirect_to_article="{% url 'article-detail' article.writer.user article.article_url %}"></div>
{% endblock %}


blog/templates/blog/article_form.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>
        {% if article %}
            {# Title of article to be updates #}
            Updating {{ article.title }} | Flove
        {% else %}
            {# Title for new article #}
            New Article | Flove
        {% endif %}
    </title>
        
        
{% endblock %}

{% block content %}
    <div class="body-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" value="Publish">
        </form>
    </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'blog/base.html' %}
{% load app_tags %}

{% block title %}
    <!-- Alternate between title for saved articles and all articles. -->
    {% url 'saved-articles' as saved_articles %}
    <title>
        {% if request.path == saved_articles %}
        Saved 
        {% endif %}
        Articles | Flove
    </title>
{% endblock %}

{% block content %}

<div class="body-content">

    <!-- Display notification for user to create writer profile if they are yet to create it. -->
    {% if user != 'AnonymousUser' and user.writer == '' %}
    <div class="info">
        <span>
            Please, kindly create your 
            <a href="{% url 'new-writer' %}" class="format-anchor">writer profile</a> 
            to have full access to features.
        </span>
    </div>
    {% endif %}

    <!-- Displays when page queryset is the list of writer's saved articles -->
    {% url 'saved-articles' as saved_articles %}
    {% if request.path == saved_articles %}
        <h1>Saved Articles</h1>
    {% endif %}

    <!-- For search of writers -->
    {% url 'search' as search_content %}
    {% if request.path == search_content %}
        <h3>{{ query_count }} result{{ query_count|pluralize }} for {{ search_data }}</h3>
        {% if writer_list %}
            <details>
                <summary class="cursor-pointer">Writers</summary>
                {% for writer in writer_list %}
                    <div class="search-writer-box">
                        <a href="{{ writer.get_absolute_url }}">
                            
                            
                            <img src="{% if writer.profile_picture %}
                            {{ writer.profile_picture.url }}
                            {% else %}
                            {{ writer.user|gravatar }}
                            {% endif %}
                            "

                            alt="{{ article.writer }}"
                            class="search-writer-img">
                            <br>
                            <small>{{ writer.first_name }}</small>
                        </a>
                    </div>
                {% endfor %}
            </details>
            <br>
        {% endif %}
    {% endif %}

    <div id="content-container">
    {% for article in article_list %}
        <!-- The if statement ensures previously saved articles are hidden when their status changes to draft. -->
        <!-- When the changes the status from public, it would be viewable again on the saved list of 
            those who had previously saved it. -->

        {% if article.article_status != 'd' %}

        <div class="article-card-cover">
            <div class="article-card">
                <div>
                    <a href="{{ article.writer.get_absolute_url }}">
                        
                        
                        <img src="{% if article.writer.profile_picture %}
                        {{ article.writer.profile_picture.url }}
                        {% else %}
                        {{ article.writer.user|gravatar }}
                        {% endif %}
                        "

                        alt="{{ article.writer }}"
                        class="article-card-writer-img">
                        <small class="article-card-writer-name">{{ article.writer }}</small>
                    </a>
                </div>
                <a href="{{ article.get_absolute_url }}">
                    {% if article.article_img %}
                        <img src="{{ article.article_img.url }}" alt="" class="article-card-img">
                    {% endif %}
                    <div class="article-card-text">
                        <h3>{{ article.title }}</h3>
                        <p>{{ article.text|safe|truncatechars_html:100 }}</p>
                        <small>{{ article.get_article_status_display }}</small>
                    </div>
                </a>

                {% if request.user.writer.id == article.writer.id %}
                <a href="{% url 'update-article' article.writer.user article.article_url %}" title="Edit" class="modify-article-icon"><i class="fa-solid fa-pen-nib"></i></a>
                <a href="{% url 'delete-article' article.writer.user article.article_url %}" title="Delete" class="modify-article-icon"><i class="fa-solid fa-trash"></i></a>
                {% endif %}
            </div>
            <hr>
        </div>
        {% endif %}
    {% empty %}
        <p>There are no articles</p>

    {% endfor %}
    
    </div>
    {% if page_obj.has_next %}
        <div id="load-more-button-div">
            <button id="load-more-button">Load More</button>
        </div>
    {% endif %}
</div>
<div id="check-authenticaton", data-check_authentication="{{ user.is_authenticated|lower }}"></div>
<div id="login-page-redirect" data-login_page_redirect="{% url 'login' %}?next={{ request.path }}"></div>
<div id="article-url" data-article_url="{% url 'articles' %}"></div>
<div id="article-pages-num" data-article_pages_num="{{ page_obj.paginator.num_pages }}"></div>

{% endblock %}

blog/templates/blog/comment_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>Delete Comment | Flove</title>
{% endblock %}

{% block content %}

    <div class="body-content">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete your comment:</p> 
            <em>{{ comment.text }}</em>
            <p>in {{ comment.article }}.</p>
            {{ form }}

            <input type="submit" value="Yes">
            <input type="submit" class="delete-cancel-button" value="Cancel">
        </form>
    </div>

    <!-- Data value that would be sent to external JavaScript to cancel delete -->
    <div id="cancel-delete-redirect-to-article", data-cancel_delete_redirect_to_article="{% url 'article-detail' comment.article.writer.user comment.article.article_url %}"></div>
{% endblock %}

blog/templates/blog/reply_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>Delete Comment | Flove</title>
{% endblock %}

{% block content %}

    <div class="body-content">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete your reponse:<p>
                
            <em>{{ reply.reply_text }}</em>
                
            <p>in {{ reply.article }}.</p>
                
            {{ form }}

            <input type="submit" value="Yes">
            <input type="submit" class="delete-cancel-button" value="Cancel">
        </form>
    </div>

    <!-- Data value that would be sent to external JavaScript to cancel delete -->
    <div id="cancel-delete-redirect-to-article", data-cancel_delete_redirect_to_article="{% url 'article-detail' reply.article.writer.user reply.article.article_url %}"></div>
{% endblock %}

blog/templates/blog/user_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>Delete {{ user }} | Flove</title>
{% endblock %}

{% block content %}

    <div class="body-content">
        <form method="post">
            {% csrf_token %}
            <h2 class="delete">Delete Account?</h2>
            <p>Are you sure you want to delete your account?</p>
            {{ form }}

            <input type="submit" value="Yes">
            <input type="submit" class="delete-cancel-button" value="Cancel">
        </form>
    </div>

    <!-- Data value that would be sent to external JavaScript to cancel delete -->
    <div id="cancel-delete-redirect-to-article", data-cancel_delete_redirect_to_article="{% url 'writer' user %}"></div>
{% endblock %}


blog/templates/blog/writer_detail.html
{% extends 'blog/base.html' %}
{% load app_tags %}

{% block title %}
    <title>
        {{ writer }} 

        {% if article_status == 'p' %}
            Public Articles 

        {% elif article_status == 'u' %}
            Unlisted Articles 

        {% elif article_status == 'd' %}
            Drafts

        {% endif %}

        | Flove
    </title>
{% endblock %}

{% block sidebar %}
    <div id="writer-page-sidebar">
        
        <img src="{% if writer.profile_picture %}
        {{ writer.profile_picture.url }}
        {% else %}
        {{ writer.user|gravatar }}
        {% endif %}"
        alt="{{ writer }}">
        
        <h3>{{ writer }}</h3>

        {% if writer.bio %}
            <b>Biography</b>
            <p>{{ writer.bio|linebreaks }}</p>
        {% endif %}

        {% if writer.display_email %}
            <b>Email</b>
            <p><a href="mailto:{{ writer.user.email }}">{{ writer.user.email }}</a></p>
        {% endif %}

        {% if writer.website_url or writer.linkedin_url %}
            <span><strong>Social Media</strong></span>
            <br>
            {% if writer.website_url %}
                <span>
                    <a href="{{ writer.website_url }}" target="_blank" title="Website">
                        <i class="fa-solid fa-globe"></i>
                    </a>
                </span>
            {% endif %}

            {% if writer.linkedin_url %}
                <span>
                    <a href="{{ writer.linkedin_url }}" target="_blank" title="LinkedIn">
                        <i class="fa-brands fa-linkedin"></i>
                    </a>
                </span>
            {% endif %}

        {% endif%}

        <!-- RSS Feed Link -->
        <span>
            <a href="{% url 'rss-feed' writer.user %}">
                <i class="fa-solid fa-rss"></i>
            </a>
        </span>
    </div>
{% endblock %}

{% block content %}
<div class="writer-page-body-content">
    {% if request.user == writer.user %}

        <!-- Form for filtering articles -->

        <form action="{% url 'filter' %}" method="get">
            <select name="article_status" id="filter">
                <option value="d" {% if article_status == 'd' %}
                selected="selected"{% endif %}>Drafts</option>

                <option value="p" {% if article_status == 'p' %}
                selected="selected"{% endif %}>Public</option>

                <option value="u" {% if article_status == 'u' %}
                selected="selected"{% endif %}>Unlisted</option>

                <option value="a" {% if article_status == None %}
                selected="selected"{% endif %}>All Published</option>

            </select>

            <input type="submit" value="Submit">
        </form>
        <br>
    {% endif %}
    
    {% for article in article_list %}

        <!-- Ensures that only user can see unlisted articles -->
        {% if article.article_status == 'u' and request.user.writer != article.writer %}
            <div></div>
        
        {% else %}
            <div class="article-card">
                <a href="{{ article.get_absolute_url }}">
                    {% if article.article_img %}
                        <img src="{{ article.article_img.url }}" alt="" class="article-card-img">
                    {% endif %}
                    <div class="article-card-text">
                        <h3>{{ article.title }}</h3>
                        <p>{{ article.text|safe|truncatechars_html:100 }}</p>
                        <small>{{ article.get_article_status_display }}</small>
                    </div>
                </a>

                {% if request.user == article.writer.user %}
                    <a href="{% url 'update-article' article.writer.user article.article_url %}" title="Edit" class="modify-article-icon"><i class="fa-solid fa-pen-nib"></i></a>
                    <a href="{% url 'delete-article' article.writer.user article.article_url %}" title="Delete" class="modify-article-icon"><i class="fa-solid fa-trash"></i></a>
                {% endif %}
            </div>
            <hr>
        {% endif %}

    {% empty %}
    <p>There are no articles</p>
    {% endfor %}

    </div>
    <div id="check-authenticaton", data-check_authentication="{{ user.is_authenticated|lower }}"></div>
    <div id="login-page-redirect" data-login_page_redirect="{% url 'login' %}?next={{ request.path }}"></div>
{% endblock %}